{% set name = "apache-airflow-providers-apache-druid" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-druid-{{ version }}.tar.gz
  sha256: 05c44d9dbd36d6601f02d0c85138a9cd20fc780d1fa3b9f91c32c4cb50bec8f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - pydruid >=0.4.1

test:
  imports:
    - airflow.providers.apache.druid
    - airflow.providers.apache.druid.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-apache-druid package
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-druid/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
